### ISSUE TITLE
API endpoint `/nmdcschema/{collection_name}`'s `next_page_token` doesn't yield next page's results

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-runtime#806] opened 2024-12-02 16:34 UTC
**Describe the bug**
When using pagination in the "/nmdcschema/{collection_name}" endpoint (with the `functional_annotation_agg` collection), the results always contain a `next_page_token` causing an infinite loop in fetching scripts. 

**To Reproduce**
```py
import requests
import time

# Get initial results (before next_page_token is given in the results)
collection = "functional_annotation_agg"
fields="was_generated_by"
max_page_size = 5000
filter = '{"was_generated_by":{"$regex":"^nmdc:wfmp"}}'

time_start = time.time()
result_list = []
og_url = f"https://api-dev.microbiomedata.org/nmdcschema/{collection}?&filter={filter}&max_page_size={max_page_size}&projection={fields}"
resp = requests.get(og_url)
initial_data = resp.json()
results = initial_data.get("resources", [])
i = 0

# append first page of results to an empty list
for result in results:
    result_list.append(result)

# if there are multiple pages of results returned
if initial_data.get("next_page_token"):
    next_page_token = initial_data["next_page_token"]

    while True:
        i = i + max_page_size
        print(str(i) + " records processed")
        url = f"https://api-dev.microbiomedata.org/nmdcschema/{collection}?&filter={filter}&max_page_size={max_page_size}&next_page_token={next_page_token}&projection={fields}"
        response = requests.get(url)
        data_next = response.json()

        results = data_next.get("resources", [])
        result_list.extend(results)
        next_page_token = data_next.get("next_page_token")

        if not next_page_token:
            break

print(len(result_list), "records found in", round(time.time() - time_start, 2), "seconds")

```

**Expected behavior**

With `max_page_size = 0`, we fetch 25118 records found in 0.51 seconds.

While pagination may take longer, I expect to retrieve the same number of records before the next_page_token is null and the loop breaks. Instead, if `max_page_size = 5000`, the loop never seems to break (I got it up to >100,000 records before recording this bug).

While this isn't an immediate blocker, we need some mechanism to fetch these records with pagination to sustain the aggregator.   

**Acceptance Criteria**
- Pagination on the "/nmdcschema/{collection_name}" with `functional_annotation_agg` endpoint should result in the same number of records as non-paginated results.

**Additional context**
We use this API call for gathering the IDs of the previously-aggregated workflows (see https://github.com/microbiomedata/nmdc-aggregator/pull/27)

**Comment by kheal** [comment] 2024-12-02 16:35
@dwinston @eecavanna - not sure if I've assigned the right folks, just wanted to make sure this was going to get the attention of the appropriate people.

**Comment by kheal** [comment] 2024-12-02 17:00
Testing this with a different collection.

` https://api-dev.microbiomedata.org/nmdcschema/workflow_execution_set?&filter={"type":"nmdc:MetaproteomicsAnalysis"}&max_page_size=10&projection=' `

returns a `next_page_token` of `nmdc:sys08k2w6w51`, but when trying to get the next page's results with this url 
` https://api-dev.microbiomedata.org/nmdcschema/workflow_execution_set?&filter={"type":"nmdc:MetaproteomicsAnalysis"}&next_page_token=nmdc:sys08k2w6w51&max_page_size=10&projection=',

They return the exact same results. Hopefully this helps narrow down the BUG.

**Comment by eecavanna** [comment] 2024-12-02 20:20
Thanks for reporting this, and for doing so this thoroughly. This does seem like a bug to me.

I think you have assigned the right people, given our current procedures. In the future, the procedure might change to: assign it to me and I'd do an initial assessment and pull in others as needed, so they can otherwise focus on whatever they've committed to for the sprint; but I'm not aware of that being the standard procedure yet (just a potential one, based upon some recent conversations).

Two things:
1. I'll look into this now.
2. The attendees of today's release planning meeting talked about this ticket. We were trying to decide whether to hold up the December 16 release for this bug. A couple of us saw that you wrote "While this isn't an immediate blocker...". It sounds to me like you have a workaround for this bug (the workaround being to not use pagination)—is that correct? If so, while we'll try to fix the bug, we won't hold up the release for it.

**Comment by eecavanna** [comment] 2024-12-02 20:21
I'll remove @dwinston as an assignee for now and will reassign him with commentary after I do some digging.

**Comment by eecavanna** [comment] 2024-12-02 20:34
Hi @kheal, I think the issue is that the endpoint is expecting the token query parameter to be named `page_token` as opposed to `next_page_token`.

![image](https://github.com/user-attachments/assets/7774b164-60a5-4557-ba38-4e8a61634b15)

I see it being named `next_page_token` in the Python snippet in the issue description:

```py
    while True:
        i = i + max_page_size
        print(str(i) + " records processed")
        url = f"https://api-dev.microbiomedata.org/nmdcschema/{collection}?&filter={filter}&max_page_size={max_page_size}&next_page_token={next_page_token}&projection={fields}"
```

Will you retry with the parameter being named `page_token` instead?

```diff
- url = f"https://api-dev.microbiomedata.org/nmdcschema/{collection}?&filter={filter}&max_page_size={max_page_size}&next_page_token={next_page_token}&projection={fields}"
+ url = f"https://api-dev.microbiomedata.org/nmdcschema/{collection}?&filter={filter}&max_page_size={max_page_size}&page_token={next_page_token}&projection={fields}"
```

**Comment by eecavanna** [comment] 2024-12-02 20:49
I confirmed that, when I name the query parameter `page_token`, the API returns a different set of resources and a different `next_page_token` value for each "page".

```console
$ curl -X GET 'https://api-dev.microbiomedata.org/nmdcschema/workflow_execution_set?&filter=%7B%22type%22%3A%22nmdc%3AMetaproteomicsAnalysis%22%7D&max_page_size=10&projection='
{"resources":[{"id":"nmdc:wfmp-11-1ky3j817.1", ...}, ...],"next_page_token":"nmdc:sys0dyggry73"}%

$ curl -X GET 'https://api-dev.microbiomedata.org/nmdcschema/workflow_execution_set?&filter=%7B%22type%22%3A%22nmdc%3AMetaproteomicsAnalysis%22%7D&max_page_size=10&projection=&page_token=nmdc:sys0dyggry73'
{"resources":[{"id":"nmdc:wfmp-11-6n1xme37.1", ...}, ...],"next_page_token":"nmdc:sys0jjz9ym68"}%

$ curl -X GET 'https://api-dev.microbiomedata.org/nmdcschema/workflow_execution_set?&filter=%7B%22type%22%3A%22nmdc%3AMetaproteomicsAnalysis%22%7D&max_page_size=10&projection=&page_token=nmdc:sys0jjz9ym68'
{"resources":[{"id":"nmdc:wfmp-11-f6sfn088.1", ...}, ...],"next_page_token":"nmdc:sys06714m695"}%
```

**Comment by kheal** [comment] 2024-12-02 21:06
User error is my favorite type of bug - sorry for the unnecessary chatter.  I'll test and close the issue after fixing the query filter.  Maybe the real issue is that there is no feedback for sending incorrect parameter keys.

**Closed** 2024-12-02 21:08 UTC
Labels: bug

**Comment by eecavanna** [comment] 2024-12-02 21:58
Thanks for including the reproduction info! I think that really reduced the time involved in identifying the root cause.

> Maybe the real issue is that there is no feedback for sending incorrect parameter keys.

I'm on my way to a meeting from 2-3pm. I'll file a ticket about that after the meeting in case one doesn't exist by then.
