### ISSUE TITLE
`load_changesheet` function tries to use Python `builtins` module to access non-Python (LinkML) data types

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#616] opened 2024-08-05 18:00 UTC
**Describe the bug**
Dev has less informative error than prod with an invalid changesheet, possibly related to changes made for https://github.com/microbiomedata/nmdc-runtime/issues/613

**To Reproduce**
1. Go to https://api-dev.microbiomedata.org/docs#/metadata/validate_changesheet_metadata_changesheets_validate_post
2. Upload a tsv with 
>
id | action | attribute | value
-- | -- | -- | --
nmdc:sty-11-547rwq94 | insert | associated_dois | 3
3 | update | doi_value | doi:10.25345/C5CG8S
  | update | doi_category | dataset_doi
  | update | doi_provider | massive
nmdc:sty-11-547rwq94 | insert | associated_dois | 4
4 | update | doi_value | doi:10.25345/C5F92D
  | update | doi_category | dataset_doi
  | update | doi_provider | massive

4. error code is 400 

```json
{
  "detail": "module 'builtins' has no attribute 'URIorCURIE'"
}
```

**Expected behavior**
Error code of 422 with validation error block in response json
```json
    "validation_errors": [
      [
        "Additional properties are not allowed ('doi_category', 'doi_provider' were unexpected)",
        "'doi_category' is a required property"
      ]
```

~Example user story template:
AS A {user|persona|system},
[INSTEAD OF {current condition}]
I EXPECTED {result}
[SO THAT {value or justification}]
[NO LATER THAN {best by date}]~

~**Screenshots**
If applicable, add screenshots to help explain your problem.~

**Acceptance Criteria**
Same behavior as on runtime prod for the changesheet:validate endpoint (422 error code with validation_error block in response json )

~Example scenario-based template:
Given (some given context or precondition), when (I take this action), then (this will be the specific outcome).~

~**Additional context**
Add any other context about the problem here.~

**Comment by aclum** [comment] 2024-08-05 18:07
Is dev down, I'm getting this 400 response code even with a valid changesheet. @eecavanna @shreddd

**Comment by aclum** [comment] 2024-08-05 18:08
example changesheet which is valid on runtime dev:


id | action | attribute | value
-- | -- | -- | --
nmdc:sty-11-547rwq94 | insert | associated_dois | 3
3 | update | doi_value | doi:10.25345/C5CG8S
3 | update | doi_category | dataset_doi
3 | update | doi_provider | massive
nmdc:sty-11-547rwq94 | insert | associated_dois | 4
4 | insert | doi_value | doi:10.25345/C5F92D
4 | insert | doi_category | dataset_doi
4 | insert | doi_provider | massive

**Comment by aclum** [comment] 2024-08-05 18:09
reassigning to @eecavanna  since i think there is something wrong with dev in general.

**Comment by eecavanna** [comment] 2024-08-05 19:14
> i think there is something wrong with dev in general.

Thanks for reporting this. I'm looking into this now.

**Comment by eecavanna** [comment] 2024-08-05 19:16
The dev Runtime is returning data for me.

![image](https://github.com/user-attachments/assets/91db2f9e-91f7-47c6-8055-bf8156a73f71)

I will now shift my focus to the specific issue mentioned in the original issue description.

**Comment by eecavanna** [comment] 2024-08-05 19:25
For everyone's reference, here are TSV files (zipped, since GitHub doesn't allow the uploading of raw TSV files) for the two tables shown above.

- From the issue description: [`nmdc-runtime.issue-616.invalid.tsv.zip`](https://github.com/user-attachments/files/16501905/nmdc-runtime.issue-616.invalid.tsv.zip)

- From [this comment](https://github.com/microbiomedata/nmdc-runtime/issues/616#issuecomment-2269624365): [`nmdc-runtime.issue-616.valid.tsv.zip`](https://github.com/user-attachments/files/16501914/nmdc-runtime.issue-616.valid.tsv.zip)

**Comment by eecavanna** [comment] 2024-08-05 19:28
I have reproduced the original issue.

![image](https://github.com/user-attachments/assets/7fb1c91e-f876-438e-9297-4bc08a8d42a8)

I will check the server logs to see whether it contains something like a stack trace.

**Comment by eecavanna** [comment] 2024-08-05 19:32
I found the corresponding line in the server logs and it did not contain any additional information compared to the HTTP response shown on Swagger UI.

![image](https://github.com/user-attachments/assets/c08e3dd4-71dd-4834-8207-2a8a2dc8644f)

I will check the source code of the endpoint in an attempt to determine what events could lead to that response being returned.

**Comment by eecavanna** [comment] 2024-08-05 19:44
In [this commit](https://github.com/microbiomedata/nmdc-runtime/commit/0318d0812bfae08f2e7d4f4ee96721d102d74fea) (made last week), the Runtime was updated to use LinkML's `SchemaView` class and Python's `builtins` module (referenced in the error response) to typecast a value parsed from the changesheet, into a Python data type.

https://github.com/microbiomedata/nmdc-runtime/blob/84bb7dec50bbc74682c04f466d317eaa07102ebf/nmdc_runtime/api/core/metadata.py#L207-L211

Based on the message in the error response, I think line 208 is setting `base_type` to something that is not a Python data type (i.e. setting it to `URIorCURIE` instead of, for example, `str`); which is breaking the `getattr(builtins, base_type)` on line 211.

CC: @dwinston

**Comment by eecavanna** [comment] 2024-08-05 19:46
In addition, the function containing the above code is called within a `try/except` pair of blocks, where the `except` block responds with an HTTP 400. That's why the response code happens to be 400.

https://github.com/microbiomedata/nmdc-runtime/blob/84bb7dec50bbc74682c04f466d317eaa07102ebf/nmdc_runtime/api/core/metadata.py#L775-L779

**Comment by eecavanna** [comment] 2024-08-05 19:55
Line 208 is using the `base` property ([docs](https://linkml.io/linkml/code/metamodel.html#linkml_runtime.linkml_model.meta.TypeDefinition.base)) of the `TypeDefinition` ([docs](https://linkml.io/linkml/code/metamodel.html#linkml_runtime.linkml_model.meta.TypeDefinition)) instance returned by the `induced_type` ([docs](https://linkml.io/linkml/developers/schemaview.html#linkml_runtime.utils.schemaview.SchemaView.induced_type)) method of the `SchemaView` instance.

https://github.com/microbiomedata/nmdc-runtime/blob/84bb7dec50bbc74682c04f466d317eaa07102ebf/nmdc_runtime/api/core/metadata.py#L205-L211

Based on the comment on line 205, I suspect the person that introduced this into the Runtime made the assumption that this `base` property referred to this thing: https://w3id.org/linkml/base

**Comment by eecavanna** [comment] 2024-08-05 20:01
I updated the issue title based upon my findings. At this point, I will reassign to @dwinston and @PeopleMakeCulture as I think they are most familiar with line 208.

**Comment by eecavanna** [comment] 2024-08-05 20:04
Hi @sierra-moxon, do you happen to know whether LinkML provides a programmatic way to determine the built-in Python data type that underlies a given `TypeDefinition` instance?

**Comment by aclum** [comment] 2024-08-05 21:30
Based on these comments I believe we should add a test coverage for where the value is a curie and one for a string, looking at https://github.com/microbiomedata/nmdc-runtime/tree/main/tests/files we have one float changesheet test and one int changesheet test.

**Comment by dwinston** [comment] 2024-08-06 17:38
I think a refactor of that block to

```python
        try:
            base_type = view.induced_type(ranges.rsplit("|", maxsplit=1)[-1]).base
            df.at[ix, "value"] = getattr(builtins, base_type)(value)
        except:
            continue
```

would solve this. In this way, the type coercion is all-or-nothing.

**Closed** 2024-08-07 15:58 UTC
Labels: bug

**Comment by aclum** [comment] 2024-08-07 16:56
confirmed fixed.
