### ISSUE TITLE
false positive validation error from queries:run

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#838] opened 2024-12-12 20:33 UTC
**Describe the bug**
I believe I'm getting a false positive validation error from queries:run, when I dump the document that runtime says is not valid, it in fact validates against the schema with linkml-validate

**To Reproduce**
1. curl command
   ```shell
   curl -X 'POST' \
     'https://api.microbiomedata.org/queries:run' \
     -H 'accept: application/json' \
     -H 'Authorization: Bearer $TOKEN' \
     -H 'Content-Type: application/json' \
     -d '
     {
      "update": "data_generation_set",
      "updates": [{"q": {"id": "nmdc:omprc-12-bk872674"}, "u": {"$set": {"has_input": ["nmdc:dobj-11-nxmk9429"]}}}]
    }'
   ```

Error is:

```json
{
  "detail": "Schema document(s) would be invalid after proposed update: {'data_generation_set': [\"{'add_date': '2022-03-25', 'gold_sequencing_project_identifiers': ['gold:Gp0618285'], 'has_input': ['nmdc:dobj-11-nxmk9429'], 'id': 'nmdc:omprc-12-bk872674', 'mod_date': '2024-01-07', 'name': 'Soil microbial communities from pasture in Falmouth, Massachusetts, USA - PETF_TOP', 'ncbi_project_name': 'Soil microbial communities from pasture in Falmouth, Massachusetts, USA - PETF_TOP', 'principal_investigator': {'email': 'nancy.hess@pnnl.gov', 'has_raw_value': 'Nancy Hess', 'name': 'Nancy Hess', 'type': 'nmdc:PersonValue'}, 'processing_institution': 'JGI', 'type': 'nmdc:NucleotideSequencing', 'analyte_category': 'metagenome', 'associated_studies': ['nmdc:sty-11-28tm5d36'], 'instrument_used': ['nmdc:inst-14-xx07be40'], 'has_output': ['nmdc:dobj-11-nxmk9429', 'nmdc:dobj-11-x7tmms98', 'nmdc:dobj-11-b7kmr176', 'nmdc:dobj-11-fj64fw53']} is not valid under any of the given schemas\"]}"
}
```

copy the result, replace single with double quotes, convert to yaml and validate with 
```console
$ poetry run linkml-validate -C NucleotideSequencing -s src/schema/nmdc.yaml test2.yaml
No issues found
```

**Expected behavior**
expected 200 response code

**Screenshots**

**Acceptance Criteria**
- Clear to everyone involved
- Can be tested or verified 
- Either passes or fails (cannot be 50% completed, for example)
- Focus on the outcome, not how the outcome is achieved
- As specific as possible (fast page load speed vs. 3-second page load speed)
- if multiple criteria, present as a bulleted list of short scenarios (see template below)

Example scenario-based template:
Given (some given context or precondition), when (I take this action), then (this will be the specific outcome).

**Additional context**
I need this to clean up some the issues from running import automation. blocks parts of https://github.com/microbiomedata/nmdc_automation/issues/333

**Comment by eecavanna** [comment] 2024-12-12 20:54
Here's a formatted version of the input JSON payload (from the `curl` command):

```json
{
    "update": "data_generation_set",
    "updates": [
        {
            "q": {
                "id": "nmdc:omprc-12-bk872674"
            },
            "u": {
                "$set": {
                    "has_input": [
                        "nmdc:dobj-11-nxmk9429"
                    ]
                }
            }
        }
    ]
}
```

**Comment by dwinston** [comment] 2024-12-12 21:02
@aclum the current (valid) document has `nmdc:bsm-11-g06qhv26` in `has_input`. I notice you are updating the input to be a DataObject versus a Biosample. Is that intended?

**Comment by dwinston** [comment] 2024-12-12 21:07
also, `nmdc:dobj-11-nxmk9429` is currently an output of <https://api.microbiomedata.org/nmdcschema/ids/nmdc:omprc-12-bk872674>. do you want to `$unset` that as you `$set` it as an input?

**Comment by dwinston** [comment] 2024-12-12 21:16
from discussion, it seems this update as expressed was not the intended update, so closing.

**Closed by dwinston** 2024-12-12 21:16 UTC
Labels: bug

**Comment by eecavanna** [comment] 2024-12-12 21:29
Thanks, @dwinston, and thanks for providing the reproduction steps, @aclum.
