### ISSUE TITLE
Cannot validate changesheets in API prod or dev

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/nmdc-runtime#277] opened 2023-07-18 18:19 UTC
When trying to use /metadata/changesheets:validate endpoint, I only get "500: Internal server error" as the server response. This happens whether logged in or not, in both https://api-dev.microbiomedata.org/ and https://api.microbiomedata.org/. Is there some kind of permissions issue? Network issue? Thank you

**Comment by dwinston** [comment] 2023-07-18 18:38
@bmeluch could you please supply the changesheet you tried, so that we can reproduce?

**Comment by eecavanna** [comment] 2023-07-18 18:39
Hi @bmeluch, thanks for reporting this.

I was able to reproduce the error by uploading an empty file to the endpoint.

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/339ea785-9ee6-4acf-a453-40de6f609245)

In contrast, when I upload the example changesheet to the same endpoint, I get a successful response.

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/da1bcb44-f82c-4602-8784-9d6b2f426591)

Because the latter worked, I don't think the former is due to a permission or network issue.

I suspect the API endpoint code was written under the assumption that the input file would meet certain conditions (such as containing TSV content with certain columns) and, when the input file does not meet them, the endpoint has an internal server error.

I'll look at the endpoint code now.

**Comment by aclum** [comment] 2023-07-18 20:02
I was able to run Bea's changesheet, further Bea is able to use other endpoint's like the [biosample endpoint](https://api.microbiomedata.org/docs#/find/find_biosamples_biosamples_get) 
Could this be a firewall issue?

**Comment by eecavanna** [comment] 2023-07-18 20:20
Hi @aclum, thanks for the update.

Commit [ac9215](https://github.com/microbiomedata/nmdc-runtime/commit/ac9215cf76e97e0457c5b79d78b889b491af3bd4) (live in both the development and production environment as of about 12:04pm PT today) fixed the original HTTP 500 Internal Server Error issue.

When I use @bmeluch's changesheet (`biosample_category.tsv`, which is 603 lines long), the Swagger UI fails to display the result. When I manually check the web browser's DevTools, though, I see a normal-looking response, so I think validation is working under the hood. However, when I delete the final 103 lines from the `biosample_category.tsv` file and try to validate the resulting 500-line file, Swagger UI works normally and shows the successful validation message. So, I think I am running into a limitation of Swagger UI (my hypothesis is that this version of Swagger UI can't show responses larger than 2 MB).

@bmeluch reported on Slack that the API rejected the original `biosample_category.tsv` file, saying it has a content type of `application/octet-stream`. I haven't reproduced that symptom yet.

@aclum, what web browser are you using, where you were able to get Swagger UI to show a successful validation result for the original `biosample_category.tsv` file?

**Comment by aclum** [comment] 2023-07-19 00:38
it was slow but I was able to do this using the ui with Chrome

**Comment by eecavanna** [comment] 2023-07-21 00:23
I think this is now fixed.

@dwinston fixed the original issue (the web server responding with HTTP 500 Internal Server Error) via commit https://github.com/microbiomedata/nmdc-runtime/commit/ac9215cf76e97e0457c5b79d78b889b491af3bd4.

With that fix in place, the API endpoint was still finding the content type of some uploaded `.tsv` files to be `application/octet-stream` as opposed to `text/tab-separated-values`. For example, for me, this happened when I uploaded a Markdown file (`README.md`), but not when uploading[ the example changesheet TSV file](https://github.com/microbiomedata/nmdc-runtime/blob/main/metadata-translation/notebooks/data/changesheet-without-separator3.tsv) (see link in screenshot below). 

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/b3f64fb8-8ed6-419e-903e-982464953786)

Meanwhile, for @bmeluch, this _did_ happen when uploading the example changesheet TSV file (as well as a TSV file named `biosample_category.tsv`).

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/a275ec27-05ec-4be1-a3ce-ac1617e9ffc8)

@dwinston fixed that issue (the API endpoint finding the content type of some uploaded `.tsv` files to be `application/octet-stream`) via commit https://github.com/microbiomedata/nmdc-runtime/commit/dd0417b03dbe27de5f9b59c6cdfd5c7a0c5e9bfb.

With that fix in place, when @bmeluch uploads that same `biosample_category.tsv` file, the API endpoint responds with a validation error. In other words, the API endpoint treats the content type as `text/tab-separated-values` and runs the normal changesheet validation code on it.

**Comment by dwinston** [comment] 2023-07-21 01:33
Agreed!

**Closed by dwinston** 2023-07-21 01:33 UTC
Labels: bug
