### ISSUE TITLE
Remove dependence upon schema variant that accepts legacy, pre-Napa IDs

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#554] opened 2024-06-13 20:29 UTC
Now that the Napa re-ID-ing has taken place, we expect all the IDs in the database to be so-called "Napa-compliant"; in other words, we expect them to not be "legacy IDs" anymore. The task here is to update the Runtime to no longer use that non-standard variant of the schema.

Here's an example where that non-standard schema variant is being referenced:

https://github.com/microbiomedata/nmdc-runtime/blob/8de5ef16ed05ca3876538dc17ef5fc2de76282c2/nmdc_runtime/util.py#L19

Here's a [related ticket](https://github.com/microbiomedata/nmdc-schema/issues/1869) in the `nmdc-schema` repo, about removing code _there_ whose sole purpose was to accommodate legacy IDs.

**Comment by PeopleMakeCulture** [comment] 2024-06-21 14:23
Closing as duplicate of https://github.com/microbiomedata/nmdc-runtime/issues/570

**Closed by PeopleMakeCulture** 2024-06-21 14:23 UTC
Labels: X SMALL
