### ISSUE TITLE
Move from piptools -> poetry

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-runtime#766] opened 2024-11-12 17:58 UTC

**Comment by eecavanna** [comment] 2024-11-13 20:51
Duplicate of: https://github.com/microbiomedata/nmdc-runtime/issues/563

**Comment by shreddd** [comment] 2024-11-15 22:46
Duplicate of: https://github.com/microbiomedata/nmdc-runtime/issues/563

**Closed** 2024-11-15 22:46 UTC
