### ISSUE TITLE
S4G1 - Data Identification for testing

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-runtime#16] opened 2021-07-13 20:14 UTC
Data identification for testing
Identify small set of raw data for processing from the same study (Pajau/Montana)
- 1 metagenome - 1 file
- 1 metaproteome - 1 file
- 1 metabolome - 1file
Put file name, sample ID, file location into a spreadsheet - manual hand-off (Pajau/Montana)

Step 1 of Goal 1 for Sprint 4
See https://docs.google.com/document/d/1iBNXkBn24ZkmJkeptoqpyjcz5PAQU59ZjMOzDObnx4E/edit?ts=60d55721#heading=h.gy54da3ooy3b for more details

**Comment by ssarrafan** [comment] 2021-07-16 21:49
After discussions with @emileyfadrosh the goal for the July sprint will be to focus on just the JGI metagenome file.  
@pvangay and @mslarae13 can you put the file name, sample ID and file location into a spreadsheet and hand off to @scanon to proceed with the second step in https://github.com/microbiomedata/nmdc-runtime/issues/17

**Comment by pvangay** [comment] 2021-07-20 20:58
Confirmed with Chris S. that this is an appropriate SPRUCE sample with metaG data to proceed with. Confirmed with lead. PI Erik L. that this is ok too.
- Sample ID in GOLD: [Gb0139007](https://gold.jgi.doe.gov/biosample?id=Gb0139007)

@scanon is using the JAMO API to fetch and stage the files - confirmed that he has already gotten the metaG raw data file for this specific sample. In the future, we should aim to fetch via a URL for an automated pipeline.

Reassigning to @scanon to proceed with next steps.

**Comment by pvangay** [comment] 2021-07-20 21:27
woops - didn't realize that there was a separate issue for Shane's task: https://github.com/microbiomedata/nmdc-runtime/issues/19

Closing this issue since this is done.

**Closed by pvangay** 2021-07-20 21:27 UTC
Labels: S4G1
