### ISSUE TITLE
Request times out: `GET /data_objects/study/{study_id}` (development environment)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#654] opened 2024-08-26 19:20 UTC
when testing on runtime dev with the neon soil data the request times out

<img width="1537" alt="Screenshot 2024-08-26 at 12 17 16 PM" src="https://github.com/user-attachments/assets/0a8a35d9-44cf-40d1-90ce-09a9e7167444">

@sujaypatil96 @eecavanna @shreddd @pkalita-lbl

**Comment by aclum** [comment] 2024-08-26 19:21
related to #401

**Comment by eecavanna** [comment] 2024-08-26 20:23
Since this is in the development environment now, it will be included in today's production release (unless we intervene).

**Comment by pkalita-lbl** [comment] 2024-08-26 20:46
Just noting that currently on production that endpoint (`GET https://api.microbiomedata.org/data_objects/study/nmdc:sty-11-34xj1150`) returns a response.

Whereas on dev that endpoint (`GET https://api-dev.microbiomedata.org/data_objects/study/nmdc:sty-11-34xj1150`) times out.

So it would appear that this is a regression from the last release.

**Comment by dwinston** [comment] 2024-09-03 17:40
something that may be opened as a separate issue, or made part of this one:

> This endpoint on dev doesn't allow for any new arguments which were in the original request. If find_data_objects_for_study_data_objects_study__study_id__get was updated on the backend to use alldocs but no other arguments are allowed this needs to be reopened.
(source: https://github.com/microbiomedata/nmdc-runtime/issues/401#issuecomment-2310889775)

**Comment by dwinston** [comment] 2024-09-03 18:00
mind for timeout issues: indexing `alldocs` fields effectively: https://github.com/microbiomedata/nmdc-runtime/blob/564f79a4671d0d9e8aa9a5fc80a32248a3d3b5f1/nmdc_runtime/api/models/util.py#L85

**Comment by eecavanna** [comment] 2024-09-05 00:29
Here's a link the Python function (source code) that processes requests sent to this endpoint.

https://github.com/microbiomedata/nmdc-runtime/blob/564f79a4671d0d9e8aa9a5fc80a32248a3d3b5f1/nmdc_runtime/api/endpoints/find.py#L129-L191

**Comment by eecavanna** [comment] 2024-09-05 00:52
Here are my notes (annotations) as I tried to understand the function.

![image](https://github.com/user-attachments/assets/7d3ba6ee-3045-478a-bcbd-a82f34c23a26)

**Comment by shreddd** [comment] 2024-09-05 01:50
@dwinston - do you know if the fields are being indexed?

**Comment by eecavanna** [comment] 2024-09-05 04:54
@shreddd, I confirmed the `id` field in `alldocs` is being indexed.

#### Details

I see an index of it in the production database (you can ignore the index on the similarly-named `_id` field):

```js
replicaset [direct: primary] nmdc> db.alldocs.getIndexes()
[
  { v: 2, key: { _id: 1 }, name: '_id_' },
  { v: 2, key: { id: 1 }, name: 'id_1', unique: true }
]
```

Also, I see this index creation statement towards the end of the Dagster operation (Python function) that generates/regenerates the `alldocs` collection.

https://github.com/microbiomedata/nmdc-runtime/blob/564f79a4671d0d9e8aa9a5fc80a32248a3d3b5f1/nmdc_runtime/site/ops.py#L1044-L1045

**Comment by eecavanna** [comment] 2024-09-05 04:54
I don't see an index on the `has_input` field, though.

**Comment by dwinston** [comment] 2024-09-05 18:00
Right, currently only the index on `id` is ensured. It would make sense to extract the definition of [`document_reference_ranged_slots`](https://github.com/microbiomedata/nmdc-runtime/blob/564f79a4671d0d9e8aa9a5fc80a32248a3d3b5f1/docs/nb/bulk_validation_referential_integrity_check.ipynb#L328) from the `bulk_validation_referential_integrity_check` notebook and ensure an index on each such slot. There aren't many; certainly fewer than the mongo collection limit (64 IIRC), and it would be appropriate to "maximally index" `alldocs`.

**Closed** 2024-09-12 22:06 UTC
