### ISSUE TITLE
Swagger UI shows dev version number in production

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#360] opened 2023-11-05 23:26 UTC
The top of the `nmdc-runtime` production Swagger UI page shows a version number that resembles the "dev" version number that I think is generated by [setuptools_scm](https://github.com/pypa/setuptools_scm).

Screenshot showing the server's console (via Rancher) and the Swagger UI served by that server:

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/59358c53-a505-420a-a12c-68687584bb10)

Link: https://api.microbiomedata.org/docs

**Comment by eecavanna** [comment] 2023-11-05 23:29
I want it to show the same version number as PyPI shows for the same "release"; in this case, `1.0.6`.

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/40dcbfdc-392f-4d37-a619-cc845b536e52)

Like this (simulated result, created by editing HTML of current web page):

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/2d06cf30-63d7-4e0c-9b91-aaf41d3b0486)

**Comment by dwinston** [comment] 2023-11-13 16:14
duplicate of #372, in that when #372 resolves, this will to.

**Closed by dwinston** 2023-11-13 16:14 UTC
Labels: bug, documentation
